name: Build library check

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.yml'
      - '**/Makefile'
      - '**/.bat'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download OpenOrbis Toolchain
      run: |
        curl -fLOs https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.416/toolchain.tar.gz
        sudo apt install llvm lld
        tar xf toolchain.tar.gz
        echo "OO_PS4_TOOLCHAIN=$GITHUB_WORKSPACE/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Build SDK Lib
      run: |
        clang -v
        make DEBUGFLAGS=1
