name: Build library check

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.yml'
      - '**/Makefile'
      - '**/.bat'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download OpenOrbis Toolchain
      run: |
        curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/latest/download/toolchain.tar.gz | tar xz -C ./
        sudo apt install llvm lld
        echo "OO_PS4_TOOLCHAIN=$GITHUB_WORKSPACE/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Build SDK Lib
      run: |
        clang -v
        make DEBUGFLAGS=1
        make PRINTF=1
        make DEBUGFLAGS=1 PRINTF=1
        make clean
        make install
